import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

/** Generated files live here (gitignored). React Router's `appDirectory` points at `.docsivi/app`. */
export const generatedDir = ".docsivi";
export const appDirectory = `${generatedDir}/app`;

const header = "// Generated by docsivi. Do not edit, do not commit.";

/** Source of `.docsivi/instance.ts`: the content macro must live in the project (it is compiled statically). */
export function renderInstance(): string {
  return `${header}
// @ts-nocheck: the project does not depend on fumadocs-mdx, so its macro has no types here. The
// type of \`docsivi\` seen by route modules is declared by "docsivi:instance" instead.
import { componentsFromGlob, createDocsivi } from "docsivi";
import { defineDocs } from "fumadocs-mdx/macro";
import config from "../docs.config.ts";

const docs = defineDocs({
  dir: "content/docs",
  docs: {
    // Only frontmatter is bundled upfront, page content is loaded on demand.
    async: true,
    // Needed for llms.txt / llms-full.txt.
    postprocess: { includeProcessedMarkdown: true },
  },
});

// custom/components/Foo.tsx becomes <Foo /> in every .mdx file.
const custom = import.meta.glob("/custom/components/*.{tsx,jsx}", { eager: true });

export const docsivi = createDocsivi(config, docs, componentsFromGlob(custom));
`;
}

export function renderRoot(hasCustomCss: boolean): string {
  return `${header}
import "docsivi/theme.css";
${hasCustomCss ? 'import "../../custom/theme.css";\n' : ""}export { default, ErrorBoundary, Layout } from "docsivi/react-router/root";
`;
}

export function renderRoutes(): string {
  return `${header}
export { default } from "docsivi/react-router/routes";
`;
}

function writeIfChanged(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  if (existsSync(path) && readFileSync(path, "utf8") === content) return;
  writeFileSync(path, content);
}

/**
 * Writes the thin files React Router needs into `.docsivi/`, so a project keeps only
 * `docs.config.ts`, `vite.config.ts` and `react-router.config.ts`. Safe to call repeatedly.
 */
export function scaffold(cwd: string = process.cwd()): void {
  const hasCustomCss = existsSync(join(cwd, "custom/theme.css"));
  writeIfChanged(join(cwd, generatedDir, "instance.ts"), renderInstance());
  writeIfChanged(join(cwd, appDirectory, "root.tsx"), renderRoot(hasCustomCss));
  writeIfChanged(join(cwd, appDirectory, "routes.ts"), renderRoutes());
}
