import { existsSync, mkdirSync, readdirSync, readFileSync, watch, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

const componentFile = /^([A-Z][A-Za-z0-9]*)\.(tsx|jsx)$/;

export interface CustomComponentsOptions {
  /** Project root. Defaults to `process.cwd()`. */
  cwd?: string;
  /** Folder with components, relative to `cwd`. */
  dir?: string;
  /** Generated registry file, relative to `cwd`. */
  out?: string;
}

const defaults = { dir: "custom/components", out: ".docsivi/components.generated.ts" } as const;

/** Names of the components found in the folder (`Foo.tsx` → `Foo`), sorted. */
export function findCustomComponents(options: CustomComponentsOptions = {}): string[] {
  const dir = join(options.cwd ?? process.cwd(), options.dir ?? defaults.dir);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .map((file) => componentFile.exec(file))
    .filter((match): match is RegExpExecArray => match !== null)
    .map((match) => `${match[1]}|${match[0]}`)
    .sort()
    .map((entry) => entry.split("|")[0] as string);
}

/** Source of the generated registry. Each component must be the default export of its file. */
export function renderRegistry(
  files: readonly { name: string; file: string }[],
  importBase: string,
): string {
  const imports = files.map((f) => `import ${f.name} from "${importBase}/${f.file}";`);
  const names = files.map((f) => f.name).join(", ");
  return [
    "// Generated by docsivi from custom/components. Do not edit, do not commit.",
    ...imports,
    "",
    `export const customComponents = { ${names} };`,
    "",
  ].join("\n");
}

/**
 * Writes the registry of `custom/components/*` (default exports, PascalCase file names) so that
 * every component is usable in `.mdx` without imports. Rewrites the file only when it changed.
 * Returns the component names.
 */
export function syncCustomComponents(options: CustomComponentsOptions = {}): string[] {
  const cwd = options.cwd ?? process.cwd();
  const dir = options.dir ?? defaults.dir;
  const out = join(cwd, options.out ?? defaults.out);

  const files = existsSync(join(cwd, dir))
    ? readdirSync(join(cwd, dir))
        .map((file) => ({ file, match: componentFile.exec(file) }))
        .filter((f) => f.match !== null)
        .map((f) => ({ name: f.match?.[1] as string, file: f.file }))
        .sort((a, b) => a.name.localeCompare(b.name))
    : [];

  const importBase = relative(dirname(out), join(cwd, dir)).split("\\").join("/");
  const source = renderRegistry(
    files.map((f) => ({ name: f.name, file: f.file.replace(/\.(tsx|jsx)$/, "") })),
    importBase,
  );

  mkdirSync(dirname(out), { recursive: true });
  const current = existsSync(out) ? readFileSync(out, "utf8") : null;
  if (current !== source) writeFileSync(out, source);
  return files.map((f) => f.name);
}

/** Dev only: regenerates the registry when a component file is added, removed or renamed. */
export function watchCustomComponents(options: CustomComponentsOptions = {}): void {
  const dir = join(options.cwd ?? process.cwd(), options.dir ?? defaults.dir);
  if (!existsSync(dir)) return;
  let timer: ReturnType<typeof setTimeout> | undefined;
  const watcher = watch(dir, () => {
    clearTimeout(timer);
    timer = setTimeout(() => syncCustomComponents(options), 50);
  });
  watcher.unref();
}
