import { defineI18n } from "fumadocs-core/i18n";
import type { MetaData, Source } from "fumadocs-core/source";
import { llms, loader } from "fumadocs-core/source";
import { lucideIconsPlugin } from "fumadocs-core/source/plugins/lucide-icons";
import type { TableOfContents } from "fumadocs-core/toc";
import type { MDXContent } from "mdx/types";
import type { DocsConfig } from "./config/index.ts";

/** Frontmatter and metadata available for every page without loading its content. */
export interface DocsPageData {
  title: string;
  description?: string | undefined;
  full?: boolean | undefined;
  /** Text of the page (needs `postprocess.includeProcessedMarkdown`), used by llms.txt. */
  getText?: ((type: "raw" | "processed") => Promise<string>) | undefined;
}

/** A page of the collection: metadata now, compiled content on demand. */
export interface DocsEntry extends DocsPageData {
  /** Loads the compiled content (memoized, safe to call in render with `use()`). */
  load(): Promise<{ toc: TableOfContents }>;
  /** Loads the content ahead of render so `body` does not suspend. */
  preload(): Promise<void>;
  body: MDXContent;
}

/**
 * The async collection returned by `defineDocs()` from `fumadocs-mdx/macro`. The macro is called in
 * `.docsivi/instance.ts` (generated by the Vite plugin) because it cannot be re-exported.
 */
export interface DocsCollection {
  toFumadocsSource(): Source<{ pageData: DocsPageData; metaData: MetaData }>;
  getPage(path: string): DocsEntry | undefined;
}

/**
 * Builds everything the docs site needs at runtime from the validated config and the content
 * collection.
 */
export function createDocsivi(
  config: Readonly<DocsConfig>,
  docs: DocsCollection,
  /** Components discovered in `custom/components`. */
  customComponents: Record<string, unknown> = {},
) {
  const i18n = defineI18n({
    defaultLanguage: config.i18n.defaultLanguage,
    languages: config.i18n.languages,
  });

  const source = loader({
    baseUrl: "/docs",
    source: docs.toFumadocsSource(),
    i18n,
    // `icon: "Rocket"` in frontmatter and meta.json (any Lucide icon name)
    plugins: [lucideIconsPlugin()],
  });

  const docsLlms = llms(source, {
    renderPage: async (page) =>
      `# ${page.data.title} (${page.url})\n\n${(await page.data.getText?.("processed")) ?? ""}`,
  });

  return { config, i18n, source, docs, customComponents, docsLlms };
}

export type Docsivi = ReturnType<typeof createDocsivi>;

/**
 * Turns the result of `import.meta.glob("/custom/components/*.{tsx,jsx}", { eager: true })` into a
 * component map: file name = tag name (PascalCase), default export = component.
 */
export function componentsFromGlob(modules: Record<string, unknown>): Record<string, unknown> {
  const components: Record<string, unknown> = {};
  for (const [path, mod] of Object.entries(modules)) {
    const name = /([A-Z][A-Za-z0-9]*)\.(?:tsx|jsx)$/.exec(path)?.[1];
    const component = (mod as { default?: unknown } | null)?.default;
    if (name && component) components[name] = component;
  }
  return components;
}
